import type { MiniApp } from "@baristapp/shared";
import { getLLMProvider } from "../llm/providerFactory";
import { createToolRegistry } from "../worker/toolRegistry";
import { runAgentWorker } from "../worker/agentWorker";
import { runAiderWorker } from "../worker/aiderWorker";
import { runSpecTests } from "../../validation/specTester";
import { deployMiniAppToSandbox } from "../runtime/sandboxManager";
import {
  loadLatestDeployment,
  listAppVersions,
  saveAppDeployment,
  saveAppSpec,
  saveAppVersion,
} from "../supabaseClient";
import { emitOrchestrationEvent } from "./orchestrationEvents";
import L from "../../utils/logger";

export interface OrchestratedGenerationResult {
  success: true;
  miniApp: MiniApp;
  usage: {
    modelName: string;
    costUsd: number;
    numTurns: number;
  };
  artifact: {
    versionId: string | null;
    testsPassed: boolean;
  };
  testReport: {
    passed: boolean;
    checks: string[];
  };
  previewUrl?: string;
  iterationLog: Array<{ iteration: number; action: "draft" | "repair" | "test"; ok: boolean; message: string }>;
}

export interface OrchestratedFailureResult {
  success: false;
  error: string;
}

export type OrchestratedResult = OrchestratedGenerationResult | OrchestratedFailureResult;

const inFlightGenerations = new Map<string, number>();

function enterGenerationSlot(userId: string): boolean {
  const maxConcurrent = Number(process.env.MAX_CONCURRENT_GENERATIONS_PER_USER ?? 2);
  const current = inFlightGenerations.get(userId) ?? 0;
  if (current >= maxConcurrent) return false;
  inFlightGenerations.set(userId, current + 1);
  return true;
}

function leaveGenerationSlot(userId: string): void {
  const current = inFlightGenerations.get(userId) ?? 0;
  if (current <= 1) {
    inFlightGenerations.delete(userId);
    return;
  }
  inFlightGenerations.set(userId, current - 1);
}

function summarizeChecks(checks: string[]): string {
  if (checks.length === 0) return "All checks passed";
  return checks.slice(0, 4).join("; ");
}

export async function createMiniAppWithOrchestrator(
  userId: string,
  prompt: string
): Promise<OrchestratedResult> {
  if (!enterGenerationSlot(userId)) {
    return {
      success: false,
      error: "You already have too many app generations running. Please retry in a few moments.",
    };
  }

  const provider = getLLMProvider();
  const maxIterations = Math.max(1, Number(process.env.AGENT_MAX_ITERATIONS ?? 3));
  const executorMode = (process.env.AGENT_EXECUTOR_MODE ?? "native").toLowerCase();
  L.log("AGENT", `Orchestrator start user=${userId}`);
  L.detail("AGENT", "Provider", provider.providerName);
  L.detail("AGENT", "Executor", executorMode);
  L.detail("AGENT", "Max iterations", maxIterations);
  L.detail("AGENT", "Prompt chars", prompt.length);

  try {
    emitOrchestrationEvent({
      userId,
      appId: "pending",
      stage: "start",
      message: "Starting app creator worker",
      metadata: { provider: provider.providerName, maxIterations },
    });

    let worker:
      | Awaited<ReturnType<typeof runAgentWorker>>
      | {
          success: boolean;
          miniApp?: MiniApp;
          testReport: { passed: boolean; checks: string[] };
          iterationLog: Array<{ iteration: number; action: "draft" | "repair" | "test"; ok: boolean; message: string }>;
          error?: string;
        };

    if (executorMode === "aider") {
      L.log("AGENT", "Aider executor enabled");
      const aider = await runAiderWorker(prompt);
      if (aider.success && aider.miniApp) {
        const aiderTests = runSpecTests(aider.miniApp);
        const aiderChecks = [...aiderTests.errors, ...aiderTests.warnings];
        if (aiderTests.errors.length > 0) {
          L.warn("AGENT", `Aider spec has ${aiderTests.errors.length} errors, ${aiderTests.warnings.length} warnings`);
        }
        worker = {
          success: true,
          miniApp: aider.miniApp,
          testReport: { passed: aiderTests.passed, checks: aiderChecks },
          iterationLog: [
            { iteration: 1, action: "draft", ok: true, message: "Generated by Aider worker" },
            { iteration: 1, action: "test", ok: aiderTests.passed, message: aiderTests.passed ? "Spec tests passed" : `${aiderTests.errors.length} errors: ${aiderTests.errors.slice(0, 3).join("; ")}` },
          ],
        };
      } else if ((process.env.AIDER_FALLBACK_NATIVE ?? "true").toLowerCase() === "true") {
        L.warn("AGENT", `Aider failed, falling back to native worker: ${aider.error ?? "unknown error"}`);
        worker = await runAgentWorker({
          provider,
          prompt,
          maxIterations,
          tools: createToolRegistry(process.cwd()),
        });
      } else {
        worker = {
          success: false,
          testReport: { passed: false, checks: ["Aider execution failed"] },
          iterationLog: [{ iteration: 1, action: "draft", ok: false, message: aider.error ?? "Aider failed" }],
          error: aider.error ?? "Aider execution failed",
        };
      }
    } else {
      worker = await runAgentWorker({
        provider,
        prompt,
        maxIterations,
        tools: createToolRegistry(process.cwd()),
      });
    }

    if (!worker.success || !worker.miniApp) {
      return {
        success: false,
        error: worker.error ?? "App creator worker failed",
      };
    }

    const app = worker.miniApp;
    L.success("AGENT", `Worker completed for ${app.appId}`);
    L.detail("AGENT", "Iteration count", worker.iterationLog.length);
    emitOrchestrationEvent({
      userId,
      appId: app.appId,
      stage: "validation",
      message: worker.testReport.passed ? "Spec checks passed" : "Spec checks failed",
      metadata: { checks: worker.testReport.checks },
    });

    await saveAppSpec(userId, app.appId, app);

    // Versioning is optional — tables may not exist for fresh/local setups
    let version: Awaited<ReturnType<typeof saveAppVersion>> = null;
    try {
      const previousVersion = (await listAppVersions(userId, app.appId))[0];
      version = await saveAppVersion({
        userId,
        appId: app.appId,
        parentVersionId: previousVersion?.id ?? null,
        sourceRequestType: "generate",
        commitMessage: "Generated app via orchestrator worker",
        diffSummary: summarizeChecks(worker.testReport.checks),
        testsPassed: worker.testReport.passed,
        spec: app,
      });
    } catch (versionErr) {
      L.warn("AGENT", `Versioning skipped — ${versionErr instanceof Error ? versionErr.message : String(versionErr)}`);
    }

    emitOrchestrationEvent({
      userId,
      appId: app.appId,
      stage: "versioning",
      message: "Persisted app version",
      metadata: { versionId: version?.id ?? null },
    });

    const deployment = await deployMiniAppToSandbox(
      app.appId,
      version?.id ?? "unversioned",
      app
    );
    L.detail("AGENT", "Deploy provider", deployment.provider);
    L.detail("AGENT", "Deploy status", deployment.status);
    if (version?.id) {
      try {
        await saveAppDeployment({
          userId,
          appId: app.appId,
          versionId: version.id,
          provider: deployment.provider,
          status: deployment.status,
          previewUrl: deployment.previewUrl ?? null,
          runtimeId: deployment.sandboxId ?? null,
          healthStatus: deployment.healthCheck?.message ?? null,
        });
      } catch (deployErr) {
        L.warn("AGENT", `Deployment record skipped — ${deployErr instanceof Error ? deployErr.message : String(deployErr)}`);
      }
    }

    emitOrchestrationEvent({
      userId,
      appId: app.appId,
      stage: "deploy",
      message: deployment.status,
      metadata: { previewUrl: deployment.previewUrl ?? null },
    });

    let latestDeployment: Awaited<ReturnType<typeof loadLatestDeployment>> = null;
    try {
      latestDeployment = await loadLatestDeployment(userId, app.appId);
    } catch {
      // deployment lookup table may not exist
    }
    return {
      success: true,
      miniApp: app,
      usage: {
        modelName: `${provider.providerName}:agent-worker`,
        costUsd: 0,
        numTurns: worker.iterationLog.length,
      },
      artifact: {
        versionId: version?.id ?? null,
        testsPassed: worker.testReport.passed,
      },
      testReport: worker.testReport,
      previewUrl: latestDeployment?.previewUrl ?? deployment.previewUrl,
      iterationLog: worker.iterationLog,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { success: false, error: message };
  } finally {
    leaveGenerationSlot(userId);
  }
}

export async function modifyMiniAppWithOrchestrator(
  userId: string,
  currentSpec: MiniApp,
  modifyPrompt: string
): Promise<OrchestratedResult> {
  const provider = getLLMProvider();
  L.log("AGENT", `Orchestrator modify start user=${userId} app=${currentSpec.appId}`);
  L.detail("AGENT", "Provider", provider.providerName);
  L.detail("AGENT", "Prompt chars", modifyPrompt.length);
  const result = await provider.modifyMiniApp(currentSpec, modifyPrompt);
  if (!result.success) return result;

  const app = result.miniApp;
  const modifyTests = runSpecTests(app);
  if (modifyTests.errors.length > 0) {
    L.warn("AGENT", `Modify spec has ${modifyTests.errors.length} errors`);
    for (const e of modifyTests.errors) L.detail("AGENT", "  ERR", e);
  }

  await saveAppSpec(userId, app.appId, app);

  let version: Awaited<ReturnType<typeof saveAppVersion>> = null;
  try {
    const previousVersion = (await listAppVersions(userId, app.appId))[0];
    version = await saveAppVersion({
      userId,
      appId: app.appId,
      parentVersionId: previousVersion?.id ?? null,
      sourceRequestType: "modify",
      commitMessage: "Modified app via orchestrator",
      diffSummary: `Prompt: ${modifyPrompt.slice(0, 120)}`,
      testsPassed: modifyTests.passed,
      spec: app,
    });
  } catch (versionErr) {
    L.warn("AGENT", `Versioning skipped — ${versionErr instanceof Error ? versionErr.message : String(versionErr)}`);
  }

  const deployment = await deployMiniAppToSandbox(
    app.appId,
    version?.id ?? "unversioned",
    app
  );
  if (version?.id) {
    try {
      await saveAppDeployment({
        userId,
        appId: app.appId,
        versionId: version.id,
        provider: deployment.provider,
        status: deployment.status,
        previewUrl: deployment.previewUrl ?? null,
        runtimeId: deployment.sandboxId ?? null,
        healthStatus: deployment.healthCheck?.message ?? null,
      });
    } catch (deployErr) {
      L.warn("AGENT", `Deployment record skipped — ${deployErr instanceof Error ? deployErr.message : String(deployErr)}`);
    }
  }

  const modifyChecks = [...modifyTests.errors, ...modifyTests.warnings];
  return {
    success: true,
    miniApp: app,
    usage: result.usage,
    artifact: {
      versionId: version?.id ?? null,
      testsPassed: modifyTests.passed,
    },
    testReport: { passed: modifyTests.passed, checks: modifyChecks },
    previewUrl: deployment.previewUrl,
    iterationLog: [
      {
        iteration: 1,
        action: "draft",
        ok: true,
        message: "Modify request completed",
      },
      {
        iteration: 1,
        action: "test",
        ok: modifyTests.passed,
        message: modifyTests.passed
          ? `Tests passed (${modifyTests.warnings.length} warnings)`
          : `${modifyTests.errors.length} errors: ${modifyTests.errors.slice(0, 3).join("; ")}`,
      },
    ],
  };
}
